Dotteam/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dotteam.Data;
using Dotteam.Models;
using Microsoft.AspNetCore.Authorization;

namespace Dotteam.Controllers
{
    public class CommentController : Controller
    {
        private readonly DotteamContext _context;

        public CommentController(DotteamContext context)
        {
            _context = context;
        }

        // GET: Comment
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            var dotteamContext = _context.CommentModel.Include(c => c.ParentComment).Include(c => c.Presentaion);
            return View(await dotteamContext.ToListAsync());
        }

        // GET: Comment/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commentModel = await _context.CommentModel
                .Include(c => c.ParentComment)
                .Include(c => c.Presentaion)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (commentModel == null)
            {
                return NotFound();
            }

            return View(commentModel);
        }

        // GET: Comment/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["ReplyToCommentId"] = new SelectList(_context.CommentModel, "Id", "Name");
            ViewData["PresentationId"] = new SelectList(_context.PresentaionModel, "Id", "Name");
            return View();
        }

        // POST: Comment/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Title,Text,CreatedAt,State,PresentationId,ReplyToCommentId")] CommentModel commentModel)
        {
            if (ModelState.IsValid)
            {
                commentModel.CreatedAt = DateTime.Now;
                commentModel.State = "Show";
                _context.Add(commentModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ReplyToCommentId"] = new SelectList(_context.CommentModel, "Id", "Name", commentModel.ReplyToCommentId);
            ViewData["PresentationId"] = new SelectList(_context.PresentaionModel, "Id", "Name", commentModel.PresentationId);
            return View(commentModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAjax([Bind("Id,Name,Email,Title,Text,CreatedAt,State,PresentationId,ReplyToCommentId")] CommentModel commentModel)
        {
            if (ModelState.IsValid)
            {
                commentModel.CreatedAt = DateTime.Now;
                commentModel.State = "Show";
                _context.Add(commentModel);
                await _context.SaveChangesAsync();
                return Json(true);
            }
            return Json(false);
        }

        // GET: Comment/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commentModel = await _context.CommentModel.FindAsync(id);
            if (commentModel == null)
            {
                return NotFound();
            }
            ViewData["ReplyToCommentId"] = new SelectList(_context.CommentModel, "Id", "Name", commentModel.ReplyToCommentId);
            ViewData["PresentationId"] = new SelectList(_context.PresentaionModel, "Id", "Name", commentModel.PresentationId);
            return View(commentModel);
        }

        // POST: Comment/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Title,Text,CreatedAt,State,PresentationId,ReplyToCommentId")] CommentModel commentModel)
        {
            if (id != commentModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(commentModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentModelExists(commentModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ReplyToCommentId"] = new SelectList(_context.CommentModel, "Id", "Name", commentModel.ReplyToCommentId);
            ViewData["PresentationId"] = new SelectList(_context.PresentaionModel, "Id", "Name", commentModel.PresentationId);
            return View(commentModel);
        }

        // GET: Comment/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commentModel = await _context.CommentModel
                .Include(c => c.ParentComment)
                .Include(c => c.Presentaion)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (commentModel == null)
            {
                return NotFound();
            }

            return View(commentModel);
        }

        // POST: Comment/Delete/5
        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var commentModel = await _context.CommentModel.FindAsync(id);
            _context.CommentModel.Remove(commentModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommentModelExists(int id)
        {
            return _context.CommentModel.Any(e => e.Id == id);
        }
    }
}

Dotteam/Controllers/IssueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dotteam.Data;
using Dotteam.Models;
using Microsoft.AspNetCore.Authorization;

namespace Dotteam.Controllers
{
    [Authorize(Roles = "Admin")]
    public class IssueController : Controller
    {
        private readonly DotteamContext _context;

        public IssueController(DotteamContext context)
        {
            _context = context;
        }

        // GET: Issue
        public async Task<IActionResult> Index()
        {
            var dotteamContext = _context.IssueModel.Include(i => i.Project);
            return View(await dotteamContext.ToListAsync());
        }

        // GET: Issue/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var issueModel = await _context.IssueModel
                .Include(i => i.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (issueModel == null)
            {
                return NotFound();
            }
            
            return View(issueModel);
        }

        // GET: Issue/Create
        public IActionResult Create()
        {
            ViewData["ProjectId"] = new SelectList(_context.ProjectModel, "Id", "Name");
            return View();
        }

        // POST: Issue/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,ProjectId")] IssueModel issueModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(issueModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(_context.ProjectModel, "Id", "Name", issueModel.ProjectId);
            return View(issueModel);
        }

        // GET: Issue/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var issueModel = await _context.IssueModel.FindAsync(id);
            if (issueModel == null)
            {
                return NotFound();
            }
            ViewData["ProjectId"] = new SelectList(_context.ProjectModel, "Id", "Name", issueModel.ProjectId);
            return View(issueModel);
        }

        // POST: Issue/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,ProjectId")] IssueModel issueModel)
        {
            if (id != issueModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(issueModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IssueModelExists(issueModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(_context.ProjectModel, "Id", "Name", issueModel.ProjectId);
            return View(issueModel);
        }

        // GET: Issue/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var issueModel = await _context.IssueModel
                .Include(i => i.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (issueModel == null)
            {
                return NotFound();
            }

            return View(issueModel);
        }

        // POST: Issue/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var issueModel = await _context.IssueModel.FindAsync(id);
            _context.IssueModel.Remove(issueModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IssueModelExists(int id)
        {
            return _context.IssueModel.Any(e => e.Id == id);
        }
    }
}

Dotteam/Views/Shared/_CommentBox.cshtml
@model Dotteam.Models.CommentModel

<hr />

<h3 class="mb-4">Leave us a comment!</h3>

<div name="comment-form">
    <form id="comment_form" asp-controller="Comment" asp-action="Create" method="post">
        <div class="row">
            <input type="hidden" asp-for="PresentationId" />
            <div class="col-md-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>*
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>*
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>*
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Text" class="control-label"></label>*
            <textarea asp-for="Text" class="form-control"></textarea>
            <span asp-validation-for="Text" class="text-danger"></span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Send</button>
        </div>
    </form>
</div>

Dotteam/Views/Shared/_CommentSection.cshtml
@model IEnumerable<Dotteam.Models.CommentModel>


<hr />
@if (Model.Count() > 0)
{
    <h2 class="mb-5">Latest Comments</h2>

    @foreach (var comment in Model)
    {
        <div class="d-flex flex-row comment-row mb-5 p-4">
            <div class="pr-2"><img src="~/images/user_default.png" alt="user" width="50" class="rounded-circle"></div>
            <div class="comment-text w-100">
                <span class="float-right badge badge-secondary">@comment.CreatedAt.ToString("yyyy/MM/dd - HH:mm")</span>
                <h6 class="h6 small">@comment.Name (@comment.Email) says:</h6>
                <p class="mb-3 pl-3">
                    <span class="h5">@comment.Title; </span>
                    @comment.Text
                </p>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                {
                    <div class="comment-footer">
                        <button type="button" class="btn btn-cyan btn-sm">Edit</button> <button type="button" class="btn btn-success btn-sm">Publish</button> <button type="button" class="btn btn-danger btn-sm">Delete</button>
                    </div>
                }
            </div>
        </div>
    }
}
else
{ <h2>No Comments yet</h2>}

Dotteam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/icons/favicon.png" type="image/png" sizes="16x16">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="DOTteam; a growing and flurishing Web Develping Company founded in 2011, Mashhad, Khorasan Razavi, Iran.">
    <meta name="keywords" content="Web Application, Web Service, Web Design, UI/UX, HTML, CSS, Javascript, PHP, ASP.NET CORE, Android, iOs, Flutter">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,700%7CRoboto:300,400,500%7CMuli:300,400" rel="stylesheet">
    <link rel="stylesheet" href="~/css/animate.css"> <!-- Resource style -->
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/owl.theme.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/ionicons.min.css"> <!-- Resource style -->
    <link href="~/css/custom.css" rel="stylesheet" type="text/css" media="all" />
  </head>
  <body>

      <div class="wrapper">
          <nav class="navbar navbar-default navbar-fixed-top">
              <div class="container">
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header page-scroll">
                      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                      </button>
                      <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                          <img class="img-responsive pull-left" src="~/icons/favicon.png" width="18" style="margin-right: 0.3em;" /> DOT
                      </a>
                  </div>
                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
                      <ul class="nav navbar-nav">
                          <partial name="_LoginPartial" />
                          @if (IsSectionDefined("Navbar"))
                          {
                              @RenderSection("Navbar")
                          }
                          else
                          {
                              <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                              <li><a asp-controller="Project" asp-action="Index">Projects</a></li>
                              @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                              {
                                  <li><a asp-controller="Issue" asp-action="Index">Issues</a></li>
                                  <li><a asp-controller="Comment" asp-action="Index">Comment</a></li>
                              }
                              <li><a asp-controller="Home" asp-action="Index">Contact Us</a></li>
                          }
                      </ul>
                  </div>
              </div>
          </nav><!-- /.navbar-collapse -->

          <div id="main" class="main">


              @RenderBody()


              <div class="footer">
                  <div class="container">
                      <div class="row">
                          <div class="col-sm-5">
                              <div class="ft-left">
                                  <div class="footer-img">
                                      <img src="~/icons/pi-logo.png" width="30" alt="Logo">
                                  </div>
                                  <p>
                                      Cu qui probo malorum saperet. Ne admodum apeirian iracundia usu, eam cu agam ludus,
                                      eum munere accusam molestie ut. Alienum percipitur ne est, pri quando iriure ad.
                                  </p>
                                  <p>&copy; 2017 YDirection Themes by IOThemes</p>
                              </div>
                          </div>
                          <div class="col-sm-4 col-sm-offset-3">
                              <div class="ft-right">
                                  <ul>
                                      <li><a href="#">About Us</a></li>
                                      <li><a href="#">Projects</a></li>
                                      <li><a href="#">Privacy policy</a></li>
                                      <li><a href="#">User Agreement</a></li>
                                      <li><a href="#">Contact</a></li>
                                  </ul>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div> <!-- Main -->
      </div><!-- Wrapper -->
      <!-- Jquery and Js Plugins -->
      <script type="text/javascript" src="~/js/jquery-2.1.1.js"></script>
      <script type="text/javascript" src="~/js/jquery.validate.min.js"></script>
      <script type="text/javascript" src="~/js/bootstrap.min.js"></script>
      <script type="text/javascript" src="~/js/plugins.js"></script>
      <script type="text/javascript" src="~/js/validator.js"></script>
      <script type="text/javascript" src="~/js/custom.js"></script>
      @RenderSection("Scripts", required: false)
  </body>
</html>



@*<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dotteam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dotteam</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Issue" asp-action="Index">Issues</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comment" asp-action="Index">Comments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Presentation" asp-action="Index">Presentations</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 1399 - Dotteam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>*@

Dotteam/Views/Shared/_Message.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var MessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@MessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}