Dotteam/Controllers/PresentationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dotteam.Data;
using Dotteam.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;

namespace Dotteam.Controllers
{
    public class PresentationController : Controller
    {
        private readonly DotteamContext _context;
        private readonly IWebHostEnvironment _env;
        private readonly string _uploadDirectory;
        private readonly string[] _permittedExtensions = { ".jpg", ".png", ".jpeg" };
        private readonly long _fileSizeLimit;

        [TempData]
        public string Message { get; set; }

        public PresentationController(DotteamContext context, IWebHostEnvironment env, IConfiguration config)
        {
            _context = context;
            _env = env;
            _uploadDirectory = Path.Combine(_env.WebRootPath, @"images\upload");
            _fileSizeLimit = config.GetValue<long>("FileSizeLimit");
        }

        // GET: Presentaion
        public async Task<IActionResult> Index()
        {
            var dotteamContext = _context.PresentaionModel.Include(p => p.Project);
            return View(await dotteamContext.ToListAsync());
        }

        // GET: Presentaion/Details/5
        public async Task<IActionResult> Details(int? id, string name)
        {
            if (id == null || name == null)
            {
                return NotFound();
            }

            var presentaionModel = await _context.PresentaionModel
                .Include(p => p.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (presentaionModel == null || presentaionModel.Name.Replace(" ", "-") != name)
            {
                return NotFound();
            }
            ViewBag.Comments = _context.CommentModel.Where(x => x.PresentationId == presentaionModel.Id).OrderBy(x => x.CreatedAt).ToList();
            return View(presentaionModel);
        }

        public async Task<IActionResult> LoadComments(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var presentaionModel = await _context.PresentaionModel
                .Include(p => p.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (presentaionModel == null)
            {
                return NotFound();
            }
            var Comments = _context.CommentModel.Where(x => x.PresentationId == presentaionModel.Id).OrderBy(x => x.CreatedAt).ToList();
            return PartialView("_CommentSection", Comments);
        }

        // GET: Presentaion/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["ProjectId"] = new SelectList(_context.ProjectModel, "Id", "Name");
            return View();
        }

        // POST: Presentaion/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("Id,Name,Image,DescriptionShort,DescriptionLong,EstimateTime,EstimatePrice,LastChange,ProjectId")] PresentaionModel presentaionModel,
                                                IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                string fullFilePath = null;
                string fileName = null;
                string uploadDirectory = _uploadDirectory;
                System.IO.Directory.CreateDirectory(uploadDirectory);

                if (imageFile != null && imageFile.Length > 0)
                {
                    string fileExt = Path.GetExtension(imageFile.FileName).ToLowerInvariant();

                    if (string.IsNullOrEmpty(fileExt) || !_permittedExtensions.Contains(fileExt))
                    {
                        Message = "Error : Invalid File Extension";
                        ViewData["ProjectId"] = new SelectList(_context.ProjectModel, "Id", "Name", presentaionModel.ProjectId);
                        return View();
                    }

                    if (imageFile.Length > _fileSizeLimit)
                    {
                        Message = "Error : File max size must be 10MB";
                        ViewData["ProjectId"] = new SelectList(_context.ProjectModel, "Id", "Name", presentaionModel.ProjectId);
                        return View();
                    }

                    do
                    {
                        fileName = Guid.NewGuid().ToString() + fileExt;
                        fullFilePath = string.Format(@"{0}\{1}", uploadDirectory, fileName);
                    } while (System.IO.File.Exists(fullFilePath));

                    using (var stream = System.IO.File.Create(fullFilePath))
                    {
                        await imageFile.CopyToAsync(stream);
                    }

                    presentaionModel.Image = string.Format(@"{0}\{1}", @"images\upload", fileName);
                }

                presentaionModel.LastChange = DateTime.Now;
                _context.Add(presentaionModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(_context.ProjectModel, "Id", "Name", presentaionModel.ProjectId);
            return View(presentaionModel);
        }

        // GET: Presentaion/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var presentaionModel = await _context.PresentaionModel.FindAsync(id);
            if (presentaionModel == null)
            {
                return NotFound();
            }
            ViewData["ProjectId"] = new SelectList(_context.ProjectModel, "Id", "Name", presentaionModel.ProjectId);
            return View(presentaionModel);
        }

        // POST: Presentaion/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id,
                                              [Bind("Id,Name,Image,DescriptionShort,DescriptionLong,EstimateTime,EstimatePrice,LastChange,ProjectId")] PresentaionModel presentaionModel,
                                              IFormFile imageFile)
        {
            if (id != presentaionModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                string fileName = null;
                string fullFilePath = null;
                string uploadDirectory = _uploadDirectory;
                System.IO.Directory.CreateDirectory(uploadDirectory);

                if (imageFile != null && imageFile.Length > 0)
                {
                    string fileExt = Path.GetExtension(imageFile.FileName);

                    if (string.IsNullOrEmpty(fileExt) || !_permittedExtensions.Contains(fileExt))
                    {
                        Message = "Error : Invalid File Extension";
                        ViewData["ProjectId"] = new SelectList(_context.ProjectModel, "Id", "Name", presentaionModel.ProjectId);
                        return View();
                    }

                    if (imageFile.Length > _fileSizeLimit)
                    {
                        Message = "Error : File max size must be 10MB";
                        ViewData["ProjectId"] = new SelectList(_context.ProjectModel, "Id", "Name", presentaionModel.ProjectId);
                        return View();
                    }

                    if (presentaionModel.Image == null) 
                    {
                        do
                        {
                            fileName = Guid.NewGuid().ToString() + fileExt;
                            fullFilePath = string.Format(@"{0}\{1}", uploadDirectory, fileName);
                        } while (System.IO.File.Exists(fullFilePath));

                        presentaionModel.Image = string.Format(@"{0}\{1}", @"images\upload", fileName);
                    }
                    else
                    {
                        fullFilePath = string.Format(@"{0}\{1}", _env.WebRootPath, presentaionModel.Image);
                    }

                    using (var stream = System.IO.File.Create(fullFilePath))
                    {
                        await imageFile.CopyToAsync(stream);
                    }

                }

                try
                {
                    presentaionModel.LastChange = DateTime.Now;
                    _context.Update(presentaionModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PresentaionModelExists(presentaionModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(_context.ProjectModel, "Id", "Name", presentaionModel.ProjectId);
            return View(presentaionModel);
        }

Dotteam/Controllers/ProjectController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Dotteam.Data;
using Dotteam.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using System.IO;
using Microsoft.AspNetCore.Http;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Dotteam.Controllers
{
    public class ProjectController : Controller
    {
        private readonly DotteamContext _context;
        private readonly IWebHostEnvironment _env;
        private readonly IConfiguration _config;

        [TempData]
        public string Message { get; set; }

        public ProjectController(DotteamContext context, IWebHostEnvironment env, IConfiguration config)
        {
            _context = context;
            _env = env;
            _config = config;
        }

        // GET: Project
        public async Task<IActionResult> Index()
        {
            return View(await _context.ProjectModel.ToListAsync());
        }

        // GET: Project/Details/5
        public async Task<IActionResult> Details(int? id, string name)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectModel = await _context.ProjectModel
                .Include(pr => pr.Teches)
                .Include(pr => pr.Presentations).ThenInclude(pre => pre.Comments)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projectModel == null)
            {
                return NotFound();
            }

            return View(projectModel);
        }

        // GET: Project/Create
        public IActionResult Create()
        {
            ViewBag.Teches = _context.TechModel.ToList();
            return View();
        }

        // POST: Project/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DescriptionShort,DescriptionLong")] ProjectModel projectModel,
                                                IFormFile imageFile,
                                                [Bind("techIds")] int[] techIds)
        {
            if (ModelState.IsValid)
            {
                var UploadImage = new UploadImage(_env, _config);
                projectModel.Image = await UploadImage.Create(imageFile);
                if (techIds != null)
                {
                    foreach (int techId in techIds)
                    {
                        var tech = _context.TechModel.First(t => t.Id == techId);
                        if(tech != null)
                            projectModel.Teches.Add(tech);
                    }
                }
                _context.Add(projectModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(projectModel);
        }

        // GET: Project/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectModel = await _context.ProjectModel.Include(y => y.Teches).FirstOrDefaultAsync(p => p.Id == id);
            if (projectModel == null)
            {
                return NotFound();
            }
            ViewBag.Teches = _context.TechModel.ToList();
            return View(projectModel);
        }

        // POST: Project/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
                                              [Bind("Id,Name,DescriptionShort,DescriptionLong,Image")] ProjectModel projectModel,
                                              IFormFile imageFile,
                                              [Bind("techIds")] int[] techIds)
        {
            if (id != projectModel.Id)
            {
                return NotFound();
            }
            projectModel = await _context.ProjectModel.Include(t => t.Teches).FirstOrDefaultAsync(p => p.Id == id);

            if (ModelState.IsValid)
            {
                if (imageFile != null)
                {
                    var UploadImage = new UploadImage(_env, _config);
                    if (projectModel.Image == null)
                    {
                        projectModel.Image = await UploadImage.Create(imageFile);
                    }
                    else
                    {
                        projectModel.Image = await UploadImage.Edit(projectModel.Image, imageFile);
                    }
                }

                try
                {
                    
                    foreach (var tech in projectModel.Teches.ToList())
                    {
                        if (!techIds.Contains(tech.Id))
                            projectModel.Teches.Remove(tech);
                    }

                    foreach (int techId in techIds)
                    {
                        if (!projectModel.Teches.Any(t => t.Id == techId))
                        {
                            var tech = _context.TechModel.First(t => t.Id == techId);
                            projectModel.Teches.Add(tech);
                        }
                    }

                    _context.Update(projectModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectModelExists(projectModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(projectModel);
        }

        // GET: Project/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectModel = await _context.ProjectModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projectModel == null)
            {
                return NotFound();
            }

            return View(projectModel);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var projectModel = await _context.ProjectModel.FindAsync(id);
            if (projectModel.Image != null)
            {
                var UploadImage = new UploadImage(_env, _config);
                UploadImage.Delete(projectModel.Image);
            }
            _context.ProjectModel.Remove(projectModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectModelExists(int id)
        {
            return _context.ProjectModel.Any(e => e.Id == id);
        }
    }
}

Dotteam/Views/Project/Create.cshtml
@model Dotteam.Models.ProjectModel

@{
    ViewData["Title"] = "Create";
}

<div class="hero-3">
    <div class="container">
        <h2 class="h2">Create new Project</h2>

        <hr />
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div class="row">
                <div class="col-md-4">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DescriptionShort" class="control-label"></label>
                        <textarea asp-for="DescriptionShort" class="form-control"></textarea>
                        <span asp-validation-for="DescriptionShort" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DescriptionLong" class="control-label"></label>
                        <textarea asp-for="DescriptionLong" class="form-control"></textarea>
                        <span asp-validation-for="DescriptionLong" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Image" class="control-label"></label>
                        <input name="imageFile" class="form-control" type="file" />
                        <input type="hidden" asp-for="Image" />
                        <span asp-validation-for="Image" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <label class="control-label">Used in teches:</label>
                    @if(ViewBag.Teches != null)
                    {
                        <div class="row">
                            @foreach (var tech in ViewBag.Teches as IEnumerable<Dotteam.Models.TechModel>)
                            {
                                <div class="form-check check-tech col-md-6">
                                    <input name="techIds" class="form-check-input" type="checkbox" value="@tech.Id" id="@tech.Id">
                                    <label class="form-check-label" for="@tech.Id">
                                        <img src="~/@tech.Image" height="40" class="img-responsive img-thumbnail" />
                                        <span>@tech.Name</span>
                                    </label>
                                </div>
                            }
                        </div>
                    }
                </div>
            </div>
            <div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-success" /> |
                    <a asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>

    </div>
</div>

Dotteam/Views/Project/Delete.cshtml
@model Dotteam.Models.ProjectModel

@{
    ViewData["Title"] = "Delete";
}

<div class="hero-3">
    <div class="container">
        <h2 class="h2">Delete</h2>
        <h3 class="h3">Are you sure you want to delete this project?</h3>
        <hr />
        <div>
            <div class="row">
                <div class="col-md-8">
                    <h3 class="h3 mb-3">@Html.DisplayFor(model => model.Name)</h3>
                    <p>@Html.DisplayFor(model => model.DescriptionShort)</p>
                    <br />
                    <p>@Html.DisplayFor(model => model.DescriptionLong)</p>
                </div>
                <div class="col-md-4">
                    <img src="~/@Html.DisplayFor(model => model.Image)" class="img-responsive img-thumbnail" />
                </div>
            </div>
            <hr />
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                <a asp-action="Index">Back to List</a>
            </form>
        </div>
    </div>
</div>

Dotteam/Views/Project/Details.cshtml
@model Dotteam.Models.ProjectModel

@{
    ViewData["Title"] = "DOT | "+Model.Name+" project";;
}

@section Navbar{
    <li><a asp-controller="Home" asp-action="index">Home</a></li>
    <li><a asp-action="index">Projects</a></li>
    <li><a class="page-scroll" href="#about">About</a></li>
    <li><a class="page-scroll" href="#presentation">Presentation</a></li>
    <a href="#subscribe" class="btn btn-nav page-scroll wow fadeInDown" data-wow-delay="0.3s"><span>Order Now</span></a>
}

<div id="main" class="main main-2">
    <div class="hero-2">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-sm-6">
                    <div class="intro">
                        <h1 class="wow fadeInDown" data-wow-delay="0.1s">@Html.DisplayFor(model => model.Name)</h1>
                        <p class="wow fadeInDown" data-wow-delay="0.2s">@Html.DisplayFor(model => model.DescriptionShort)</p>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                        {
                            <h3 class="mt-5">Project Tools</h3>
                            <hr />
                            <a class="btn btn-warning " asp-action="Edit" asp-route-id="@Model.Id"><span class="ion ion-edit"></span> Edit</a>
                            <a class="btn btn-danger " asp-action="Delete" asp-route-id="@Model.Id"><span class="ion ion-android-delete"></span> Delete</a>

                            <h3 class="mt-5">Presentation Tools</h3>
                            <hr />
                            <a class="btn btn-success" asp-action="Create" asp-controller="Presentation" asp-route-pid="@Model.Id"><span class="ion ion-android-create"></span> Create</a>
                        }
                    </div>
                </div>
                <div class="col-md-7 col-sm-6">
                    <img class="img-responsive m-auto" src="~/@Model.Image" alt="Feature">
                </div>
            </div>
        </div>
    </div><!-- Pi-Hero -->



    <div id="about" class="features-boxed">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="boxed-intro text-center wow fadeInDown">
                        <h1>About @Html.DisplayFor(model => model.Name)</h1>
                        <p>@Html.DisplayFor(model => model.DescriptionLong)</p>
                    </div>
                </div>

                @if (Model.Teches != null)
                {
                    @foreach (var tech in Model.Teches)
                    {
                        <div class="col-md-3 col-sm-4 wow fadeInDown">
                            <div class="box-inner">
                                <div class="box-icon">
                                    <img class="img-responsive" src="~/@tech.Image" alt="Feature">
                                </div>
                                <div class="box-info text-center">
                                    <h1>@tech.Name</h1>
                                </div>
                            </div>
                        </div>
                    }
                }

            </div>
        </div>
    </div>

    @if (Model.Presentations != null)
    {
        <div id="presentation" class="features">
            <div class="container">
                @foreach (var presentation in Model.Presentations as ICollection<Dotteam.Models.PresentaionModel>)
                {

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="features-text wow fadeInDown">
                                <h2 class="h2">@presentation.Name</h2>
                                <p>@presentation.DescriptionShort</p>
                                <hr />
                                <a class="btn btn-primary" asp-controller="Presentation" asp-action="Details" asp-route-id="@presentation.Id" asp-route-name="@presentation.Name.Replace(" ","-")"><span class="ion ion-eye"></span> View</a>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="features-image wow fadeInRight">
                                <img class="img-responsive" src="~/@presentation.Image" alt="Image">
                            </div>
                        </div>
                    </div>

                    @if (presentation.Comments != null)
                    {
                        <div class="row review-section">
                            <div class="col-sm-8 col-sm-offset-2">
                                <div class="reviews owl-carousel owl-theme">

                                    @foreach (var comment in presentation.Comments as ICollection<Dotteam.Models.CommentModel>)
                                    {
                                        <div class="review-single">
                                            <img class="img-circle" src="~/images/user_default.png" alt="Client Testimonoal" />
                                            <div class="review-text wow fadeInDown" data-wow-delay="0.2s">
                                                <p>
                                                    <span class="h5">@comment.Title; </span>
                                                    @comment.Text
                                                </p>
                                                <h3>- @comment.Name</h3>
                                                <h3>@comment.Email</h3>
                                                <i class="ion ion-star"></i>
                                                <i class="ion ion-star"></i>
                                                <i class="ion ion-star"></i>
                                                <i class="ion ion-star"></i>
                                                <i class="ion ion-star"></i>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    }

                }
            </div>
        </div>
    }

    @*<div id="reviews" class="review-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                    <div class="reviews owl-carousel owl-theme">
                        <div class="review-single">
                            <img class="img-circle" src="~/icons/review-1.png" alt="Client Testimonoal" />
                            <div class="review-text wow fadeInDown" data-wow-delay="0.2s">
                                <p>Going to use some lorem here. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer iaculis quis tellus ac vestibulum.  Etiam fermentum nisl ac venenatis rhoncus.</p>
                                <h3>- Thomas Young</h3>
                                <h3>Vice President Primal Inc</h3>
                                <i class="ion ion-star"></i>
                                <i class="ion ion-star"></i>
                                <i class="ion ion-star"></i>
                                <i class="ion ion-star"></i>
                                <i class="ion ion-star"></i>
                            </div>
                        </div>
                        <div class="review-single">
                            <img class="img-circle" src="~/icons/review-2.png" alt="Client Testimonoal" />
                            <div class="review-text">
                                <p>Going to use some lorem here. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer iaculis quis tellus ac vestibulum.  Etiam fermentum nisl ac venenatis rhoncus.</p>
                                <h3>- Neil Harris</h3>
                                <h3>President Proton LLC</h3>
                                <i class="ion ion-star"></i>
                                <i class="ion ion-star"></i>
                                <i class="ion ion-star"></i>
                                <i class="ion ion-star"></i>
                                <i class="ion ion-ios-star-half"></i>
                            </div>
                        </div>
                        <div class="review-single">
                            <img class="img-circle" src="~/icons/review-3.png" alt="Client Testimonoal" />
                            <div class="review-text">
                                <p>Going to use some lorem here. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer iaculis quis tellus ac vestibulum.  Etiam fermentum nisl ac venenatis rhoncus.</p>
                                <h3>- Alison Burgers</h3>
                                <h3>CEO Marga Holdings</h3>
                                <i class="ion ion-star"></i>
                                <i class="ion ion-star"></i>
                                <i class="ion ion-star"></i>
                                <i class="ion ion-star"></i>
                                <i class="ion ion-ios-star-half"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>*@

</div>